DROP TABLE IF EXISTS tweet;
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  U_Id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  Username VARCHAR(45) NOT NULL,
  Email VARCHAR(45) NOT NULL,
  PRIMARY KEY (U_Id)
);

CREATE TABLE tweet (
  T_Id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  User INT UNSIGNED NOT NULL,
  Text VARCHAR(139),
  PRIMARY KEY (T_Id),
  FOREIGN KEY (User) REFERENCES user(U_Id)
);

CREATE TABLE follows (
  F_Id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  Follower INT UNSIGNED NOT NULL,
  Followed INT UNSIGNED NOT NULL,
  PRIMARY KEY (F_Id),
  FOREIGN KEY (Follower) REFERENCES user(U_Id),
  FOREIGN KEY (Followed) REFERENCES user(U_Id)
);
